version: '2'
services:
  db:
    image: mdillon/postgis:latest
    expose:
      - "5432"
  api:
    build:
      context: ./api
    expose:
      - "3000"
    env_file: ./api/.env
    environment:
      - ENV=DEV
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=mysecretpassword
      - HOSTURL=http://localhost:8080/
    entrypoint: ./wait-for-it.sh db:5432 --timeout=35 -- ./entry.sh
  web:
    build:
      context: ./web
      dockerfile: ./docker/development
    env_file: ./web/.env
    expose:
      - "9000"
  proxy:
    image: nginx:latest
    ports:
      - "8081:443"
      - "8080:80"
