version: '2'
services:
  db:
    image: mdillon/postgis:latest
    ports:
      - "5432:5432"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    expose:
      - "3000"
    env_file: ./api/.env
    environment:
      - ENV=DEV
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=mysecretpassword
      - HOSTURL=https://www.seattlecranes.site/
    links:
      - db
    depends_on:
      - "db"
    entrypoint: ./wait-for-it.sh db:5432 --timeout=5 -- ./entry.sh
  web:
    build:
      context: ./web
      dockerfile: ./docker/production
    expose:
      - "9000"
    env_file: ./web/.env
    environment:
      - ENV=production
      - NODE_ENV=production
  proxy:
    image: nginx:latest
    volumes:
      - /etc/letsencrypt/archive/www.seattlecranes.site:/etc/letsencrypt
      - ./proxy:/etc/nginx
    links:
      - api:api
      - web:web
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
      - api
