version: '2'
services:
  db:
    extends:
      file: ./common-services.yml
      service: db
    volumes:
      - /var/lib/postgresql/data
  api:
    extends:
      file: ./common-services.yml
      service: api
    build:
      dockerfile: Dockerfile.prod
    environment:
      - ENV=PROD
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=mysecretpassword
      - HOSTURL=https://www.seattlecranes.site/
    links:
      - db
    depends_on:
      - "db"
  web:
    extends:
      file: ./common-services.yml
      service: web
    build:
      dockerfile: docker/production
    environment:
      - ENV=production
      - NODE_ENV=production
  proxy:
    extends:
      file: ./common-services.yml
      service: proxy
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./proxy:/etc/nginx
    links:
      - api:api
      - web:web
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
      - api
