FROM node:5.3

# Install netcat for port listening between containers
RUN apt-get update && apt-get install -y \
  netcat

WORKDIR /var/www/api/
#COPY ./package.json package.json
#COPY ./entry.sh entry.sh
COPY . ./

RUN npm install > /dev/null

EXPOSE 3000

CMD ["./entry.sh"]
