FROM node:5.3

WORKDIR /var/www/api/
COPY ./package.json package.json
RUN npm config set registry http://registry.npmjs.org/
RUN npm install
COPY ./__tests__ __tests__/
COPY ./migrations migrations/
COPY ./src src/
COPY ./.babelrc .babelrc
COPY ./entry.sh entry.sh
COPY ./wait-for-it.sh wait-for-it.sh

EXPOSE 3000

CMD ["./entry.sh"]
