extends:
  - airbnb-base
parser: babel-eslint
plugins:
  - react
env:
  browser: true,
  mocha: true
rules:
  import/no-unresolved: 0
  react/prop-types: 0
  object-curly-spacing: [1, "never"]
  arrow-body-style: 0
  no-return-assign: 0
  jsx-quotes: [2, "prefer-double"]
