extends: eslint:recommended
parser: babel-eslint
ecmaFeatures:
  jsx: true
plugins:
  - react
env:
  es6: true
  node: true
  browser: true
rules:
  comma-style:
    - 2
    - last
  semi:
    - 2
    - always
  comma-dangle:
    - 2
    - always-multiline
